//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.5.0.0 (NJsonSchema v10.1.15.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."

namespace PranavM.WxTechChallengeService.WebApi
{
    using System = global::System;
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.5.0.0 (NJsonSchema v10.1.15.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface IWxTechChallengeController
    {
        /// <summary>Retrieve user details</summary>
        /// <param name="x_Tracking_Id">Identifier used to track a request end-to-end</param>
        /// <returns>User details</returns>
        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<GetUserResponse>> GetUserAsync(string x_Tracking_Id = null);
    
        /// <summary>Retrieve user details</summary>
        /// <param name="x_Tracking_Id">Identifier used to track a request end-to-end</param>
        /// <param name="sortOption">The numbers of items to return</param>
        /// <returns>User details</returns>
        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<Product>>> SortProductsAsync(string x_Tracking_Id = null, SortOption? sortOption = null);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.5.0.0 (NJsonSchema v10.1.15.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class WxTechChallengeController : Controllers.BaseController
    {
        private IWxTechChallengeController _implementation;
    
        public WxTechChallengeController(IWxTechChallengeController implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Retrieve user details</summary>
        /// <param name="x_Tracking_Id">Identifier used to track a request end-to-end</param>
        /// <returns>User details</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("user")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<GetUserResponse>> GetUser([Microsoft.AspNetCore.Mvc.FromHeader(Name = "X-Tracking-Id")] string x_Tracking_Id = null)
        {
            return _implementation.GetUserAsync(x_Tracking_Id);
        }
    
        /// <summary>Retrieve user details</summary>
        /// <param name="x_Tracking_Id">Identifier used to track a request end-to-end</param>
        /// <param name="sortOption">The numbers of items to return</param>
        /// <returns>User details</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("sort")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<Product>>> SortProducts([Microsoft.AspNetCore.Mvc.FromHeader(Name = "X-Tracking-Id")] string x_Tracking_Id = null, [Microsoft.AspNetCore.Mvc.FromQuery] SortOption? sortOption = null)
        {
            return _implementation.SortProductsAsync(x_Tracking_Id, sortOption);
        }
    
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.15.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class GetUserResponse 
    {
        /// <summary>The name of the user</summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Name { get; set; }
    
        /// <summary>The token for the user</summary>
        [Newtonsoft.Json.JsonProperty("token", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Token { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.15.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class SortProductsResponse : System.Collections.ObjectModel.Collection<Product>
    {
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.15.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Product 
    {
        /// <summary>The name of the product</summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Name { get; set; }
    
        /// <summary>The price of the product</summary>
        [Newtonsoft.Json.JsonProperty("price", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public decimal Price { get; set; }
    
        /// <summary>The quantity of the product available</summary>
        [Newtonsoft.Json.JsonProperty("quantity", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Quantity { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.15.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class ErrorResponse 
    {
        /// <summary>Contains one or more errors for the requested operation</summary>
        [Newtonsoft.Json.JsonProperty("errors", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.List<ErrorDetail> Errors { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.15.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class ErrorDetail 
    {
        /// <summary>The HTTP Status code for this error</summary>
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Range(400, 599)]
        public int Status { get; set; }
    
        [Newtonsoft.Json.JsonProperty("source", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Source Source { get; set; }
    
        /// <summary>A title briefly describing the error</summary>
        [Newtonsoft.Json.JsonProperty("title", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; }
    
        /// <summary>Describes the error in detail (this specific instance of the problem)</summary>
        [Newtonsoft.Json.JsonProperty("detail", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Detail { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.15.0 (Newtonsoft.Json v12.0.0.0)")]
    public enum SortOption
    {
        [System.Runtime.Serialization.EnumMember(Value = @"Low")]
        Low = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"High")]
        High = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Ascending")]
        Ascending = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Descending")]
        Descending = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Recommended")]
        Recommended = 4,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.15.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Source 
    {
        /// <summary>Describes the path in the request body that caused the error</summary>
        [Newtonsoft.Json.JsonProperty("pointer", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Pointer { get; set; }
    
    
    }

}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108