apiVersion: v1
kind: Service
metadata:
  name: wxtechchallengesvc
  annotations:
      service.beta.kubernetes.io/azure-dns-label-name: pranavmwxtechchallenge
spec:
  type: LoadBalancer
  selector:
    app: wxtechchallengesvc
  ports:
  - port: 80
    targetPort: 80
